export const FETCH_STARTED = 'TOTAL_ASSET/FETCH_STARTED';
export const FETCH_SUCCESS = 'TOTAL_ASSET/FETCH_SUCCESS';
export const FETCH_FAILURE = 'TOTAL_ASSET/FETCH_FAILURE';
export const FETCH_RATE_STARTED = 'TOTAL_ASSET/FETCH_RATE_STARTED';
export const FETCH_RATE_SUCCESS = 'TOTAL_ASSET/FETCH_RATE_SUCCESS';
export const FETCH_RATE_FAILURE = 'TOTAL_ASSET/FETCH_RATE_FAILURE';

